# Use official Golang image as the build image
FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . ./

RUN go build -o service-a .

# Use a minimal image for the runtime
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/service-a .

EXPOSE 80

CMD ["./service-a"]
